### PR TITLE
add the ability to call /integration endpoints

### PR DESCRIPTION
**Pull request by davidcpell**
We're working on some automation that requires keeping an integration with PagerDuty up-to-date. I was hoping someone might be able to give me feedback about where this change is on the right track. 

I've been a bit confused while reading the API docs on integrations because of:
* how the usage of POST and PUT is described
* how that ^^ maps onto concepts like "adding" vs. replacing a configuration (specifically with POST)
* how the fact that some integrations allow POST and others allow POST or PUT should factor into the design
* and whether the resource we're acting on here is an "integration" or a "configuration" (and if the latter, whether integration : configuration is 1 : 1 or 1 : many)

### CODE REVIEW

**Comment by delner** [comment]
@athap Saw you had reviewed a previous PR that involved one of the files changed in this PR; is this something you could review? Or do you know someone who would be better suited?

**Comment by delner** [comment]
@gzussa You might want to look at this.

**Comment by delner** [comment]
@gmmeyer

**Comment by jeremy-lq** [comment]
@davidcpell We'll have someone take a look today. Thanks for the contribution!

**Pull request merged**
