### PR TITLE
Facade Updates

### PR DESCRIPTION
**Pull request by ChanChar**
Refactor setting instance variable in #initialize, added #deprecation_warning, minor styling fixes

### CODE REVIEW

**Comment by ChanChar** [comment]
@yannmh Maybe you could help me out but seems like I'm missing a test API key to use for the specs. Are there no preset test API keys configured for TravisCI?

**Comment by yannmh** [comment]
Sorry for the inconveniences @ChanChar. I recently switched the tests to use, but didn't realize that encrypted environment variables are not available for pull requests from forks 😱. I am fixing it 🔨 

Other than that, thanks a lot for your enhancements. I'll take a pass on it very shortly.

**Comment by ChanChar** [comment]
@yannmh You da best! Thanks!

**Comment by ChanChar** [comment]
@yannmh Sounds like a plan! Updated the specs also and used my own application and API keys. Ready for a review when you have some time. Thanks!

**Comment by ChanChar** [comment]
Also updated this PR. Review if this is the direction we want to go, else we can just toss this PR out.

**Pull request closed without merging**
